export const CREATE_PROPERTY_MUTATION =`
	mutation(
		$landlordname:String!,
		$propertyname:String!,
		$price:String!,
		$type:String!
		$description:String!,
		$latitude:String!,
		$longitude:String!,
		$location:String!,
		$area:String!,
		$amenities:String!,
		$policy:String!
		$vacancy:String!,
		$contact:String!,
		$mainimage:String!,
		$image1:String!,
		$image2:String!,
		$image3:String!,
		$image4:String!,
	){
		createProperty(input:{
			landlordname:$landlordname
			propertyname:$propertyname
			price:$price
			type:$type
			description:$description
			latitude:$latitude
			longitude:$longitude
			location:$location
			area:$area
			amenities:$amenities
			policy:$policy
			vacancy:$vacancy
			contact:$contact
			mainimage:$mainimage
			image1:$image1
			image2:$image2
			image3:$image3
			image4:$image4
		}){
			_id
			createdAt
			landlordname
			propertyname
			price
		}
	}
`
export const CREATE_COSHARING_MUTATION = `
	mutation(
		$name:String!,
		$price:String!,
		$propertytype:String!,
		$description:String!,
		$location:String!,
		$gender:String!,
		$coverimage:String!,
		$contact:String!,
	){
		createCoSharing(input:{
			name:$name
			price:$price
			propertytype:$propertytype
			description:$description
			location:$location
			gender:$gender
			coverimage:$coverimage
			contact:$contact
		}){
			_id
			name
			price
			contact
			description
			location
			coverimage
			propertytype
			gender
		}
	}
`
export const DELETE_PROPERTY_MUTATION =`
	mutation($propertyId: ID!){
		deleteProperty(propertyId:$propertyId){
			_id
		}
	}
`

export const CREATE_SERVICE_MUTATION=`
	mutation(
		$ownername:String!,
		$servicename:String!,
		$type:String!
		$location:String!,
		$area:String!,
		$description:String!,
		$contact:String!,
		$mainimage:String!,
	){
		createService(input:{
			ownername:$ownername
			servicename:$servicename
			type:$type
			description:$description
			location:$location
			area:$area
			contact:$contact
			mainimage:$mainimage
		}){
			_id
			createdAt
			servicename
		}
	}
`
export const CREATE_REVIEW_MUTATION = `
	mutation(
		$propertyId:ID!,
		$review:String!,
	){
		createReview(
				propertyId:$propertyId
				review:$review
			){
				_id
				propertyname
		}}
`
export const CREATE_USERINFO_MUTATION = `
	mutation(
		$userId:ID!,
		$phonenumber:String!,
		$location:String!
	){
		createUserInfo(
			userId:$userId,
			phonenumber:$phonenumber,
			location:$location
		){
			_id
			
		}
	}

`